  infinispan:
    server:
      endpoints:
      - securityRealm: default
        socketBinding: default
      - connectors:
          rest:
            restConnector:
              authentication:
                mechanisms: BASIC
        securityRealm: metrics
        socketBinding: metrics
